### ISSUE TITLE
How to get "skinBMZB.txt" file?

### ISSUE THREAD

**Issue by USTLZh** [chrisxyq/student-projects#1]
In sequent_ablation\params\setpare.py file, line78, it requests have a skinBMZB.txt in local files, and it has not this file in 3Diradb dataset,so how to get the skinBMZB,txt? and can i get your email to request some other querstions?

**Comment by 1Yang804** [comment]
May I ask if you know how to obtain .txt file? I also have this problem, and it has not been resolved. If you could let me know, I would be very grateful.
